### ISSUE TITLE
Expiarka na Prohajty.

### ISSUE THREAD

**Issue by nicku1** [Feerko/FeerkoPublic#4]
Na expiarce każdy gracz może nabrać expa do 10 lvl. Dopiero bo uzyskaniu 11 lvl wyskakuje informacja że z expiarki może korzystać tylko szlachta. Po uzyskaniu 10 lvl można potem normalnie enchantować.

**Comment by Feerko** [comment]
to tak ma być XD zeby zaachecic graczy
